### ISSUE TITLE
how to keep unicity if the node restart

### ISSUE THREAD

**Issue by benoitc** [fogfish/uid#2]
You're using `erlang:unique_integer` function to generating the ID. But how do you make sure it can be still unique if the node restart?

**Comment by fogfish** [comment]
I do not... 

The earlier versions (e.g. tag `v0.2.0`) tries to persists current state counter. However, next question arise: How to ensure durability of the counter state? etc. 

The library objectives are
>
> The k-ordered value consists of time-stamp with millisecond resolution (50-bit) that is used to __roughly sort__ events. The __time-stamp__ ensures distinct sorting within virtual machine where system clock is controlled by operation system. A locally monotonic padding (14-bits) prevents the collisions (Note: 14-bits allows to have about 16K allocations per millisecond).
>

Only 14bits of `erlang:unique_integer` is used to prevent collisions for any allocations within given millisecond. Both millisecond resolution time-stamp and unique integer __roughly__ guaranties uniqueness. Obviously, the change of system clock impacts on the ordering (uniqueness). I have not yet made a calculation on probability of such event taking into account a monotonic characteristics of counters.  

If you still need to derive strictly unique key then this library requires 3rd party arbitration. For example, you write object to database and abort transaction if given key is allocated to different object. 

What is your thoughts and use-case?

**Comment by benoitc** [comment]
@fogfish was looking for a way to generate a unique 64 bits integer across different machines in a decentralised way (some machines could be disconnected from others from time to time). I guess i need to go to 128 bits to achieve it, though having 64 bits integer woul dbe quite better since it takes less storage.

**Comment by fogfish** [comment]
I've been trying to find a schema to enable global uniqueness with 64 bits. You can do it but it requires a lot of constrains . The best what I can get is 96-bits bits schema `uid:g()`.

**Comment by benoitc** [comment]
forgot to close. thanks for the answer!
