### ISSUE TITLE
How to customize uid:encode64(uid:g()). Result prefix

### ISSUE THREAD

**Issue by leeyisoft** [fogfish/uid#5]
65> uid:encode64(uid:g()).
<<".5_vpkFkn3Ipls.n">>

**Comment by fogfish** [comment]
Can you please elaborate your question? What kind of prefix do you like to inject?

**Comment by leeyisoft** [comment]
> 

We now have a lot of business, instant order (" sk_[order_no]"), group purchase order ("gp_[order_no]"), enterprise purchase order ("ep_[order_no "), individual consumer order ("pc_[order_no "), We will encode these order numbers according to a specific prefix, so that we can troubleshoot problems and locate them

Of course, your library has done a good job, and I can meet the requirements like this (<<Prefix/binary, uid:encode64(uid:g())>>), but it doesn't feel perfect (maybe and I don't need to feel imperfect).

**Comment by fogfish** [comment]
Yes, I've been considering adding a namespace but I've discarded this idea from supporting in the library. I'd like to have generic one. 

I would advise you to create own "type" (e.g. CURIE https://en.wikipedia.org/wiki/CURIE). In Erlang, I am using tuple:

```erlang
-type compact()  :: {iri, prefix(), suffix()}.
```

It make your life 100% easier to deal within the app than mangling prefix to binary itself.
